spring.application.name=napirotas

spring.datasource.url=jdbc:mysql://localhost:3306/napi_banco

spring.datasource.username=napi

spring.datasource.password=napi123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=http://localhost:3000,http://localhost:4200,http://localhost:5173
